### ISSUE TITLE
Execution Failed

### ISSUE THREAD

**Issue by amalive** [MobileFirst-Platform-Developer-Center/InvokingAdapterProceduresAndroid#1]
Hi there, I download the sample code then Import into Android Studio. As you know, the project structure will be slightly different. I managed to sync the gradle but when I’m trying to run the project, I got the error.

Error:Execution failed for task ':app:dexDebug'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

Kindly assist me. Thanks :)

**Comment by IdanAdar** [comment]
The sample was not created with Gradle support. Try without Gradle and see if it works. Also note that the error as-is does not seem related to the sample itself.

**Comment by amalive** [comment]
I just create a new repo based on this sample code for Android Studio version.
https://github.com/amalive/MobileFirstInvokingAdapter

**Comment by NathanHazout** [comment]
Did it fix your issue or are you sharing it for us to investigate?

**Comment by IdanAdar** [comment]
Closing due to lack of co-operation by @amalive. Re-opening if new information can be provided.
